// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqVpTs51BZNmXpcP3dg1XRI1FQXut5OY',
    appId: '1:802141297021:web:73882efda5058bc3ced414',
    messagingSenderId: '802141297021',
    projectId: 'nairobi-vacant-houses-eeb0b',
    authDomain: 'nairobi-vacant-houses-eeb0b.firebaseapp.com',
    storageBucket: 'nairobi-vacant-houses-eeb0b.firebasestorage.app',
    measurementId: 'G-GQW7X3RXH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17QSkRj3uVmau-Ztz-4q7s8g6Zue7BeI',
    appId: '1:802141297021:android:7136d009d889b92cced414',
    messagingSenderId: '802141297021',
    projectId: 'nairobi-vacant-houses-eeb0b',
    storageBucket: 'nairobi-vacant-houses-eeb0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Nrvps9CLSu0p8CG-hfokAOYoZpIT2Z4',
    appId: '1:802141297021:ios:8be56ef20316f4b7ced414',
    messagingSenderId: '802141297021',
    projectId: 'nairobi-vacant-houses-eeb0b',
    storageBucket: 'nairobi-vacant-houses-eeb0b.firebasestorage.app',
    iosBundleId: 'com.example.nairobivacanthouses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Nrvps9CLSu0p8CG-hfokAOYoZpIT2Z4',
    appId: '1:802141297021:ios:8be56ef20316f4b7ced414',
    messagingSenderId: '802141297021',
    projectId: 'nairobi-vacant-houses-eeb0b',
    storageBucket: 'nairobi-vacant-houses-eeb0b.firebasestorage.app',
    iosBundleId: 'com.example.nairobivacanthouses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxqVpTs51BZNmXpcP3dg1XRI1FQXut5OY',
    appId: '1:802141297021:web:7272fda327d7fe9bced414',
    messagingSenderId: '802141297021',
    projectId: 'nairobi-vacant-houses-eeb0b',
    authDomain: 'nairobi-vacant-houses-eeb0b.firebaseapp.com',
    storageBucket: 'nairobi-vacant-houses-eeb0b.firebasestorage.app',
    measurementId: 'G-367B8X8Q0B',
  );
}
